// [ NAVIGATION > STACKS > MAIN ] ##################################################################

// 1.1. EXTERNAL DEPENDENCIES ......................................................................
import React from 'react'
import { useSelector } from 'react-redux'
import { createNativeStackNavigator } from '@react-navigation/native-stack'
// 1.1. END ........................................................................................

// 1.2. INTERNAL DEPENDENCIES ......................................................................

import HomePage from '../../../components/pages/home/home'
import DetailsPage from '../../../components/pages/details/details'
import { selectUserRole } from '../../../redux/selectors/user'
import { commonScreenOptions } from '../../../utils/logic/screenOptions'
// 1.2. END ........................................................................................

// 1.3. IMAGES .....................................................................................
// 1.3. END ........................................................................................

// 1.4. DATA .......................................................................................
// 1.4. END ........................................................................................

// 1.5. GLOBALS ....................................................................................
// 1.5.END .........................................................................................

// 1.5. COMPONENT ..................................................................................

const Root: React.FC = () => {
  // 1.5.1. HOOKS & API CALLS ....................................................................
  const userRole = useSelector(selectUserRole)
  // 1.5.1. END ..................................................................................

  // 1.5.2. FUNCTIONS & LOCAL VARIABLES ..........................................................
  const Stack = createNativeStackNavigator()

  const initialRouteName = userRole === 'DRIVER' ? 'Shipments' : 'Home'
  // 1.5.2. END ..................................................................................

  // 1.5.3. RENDER ...............................................................................

  return (
    <Stack.Navigator initialRouteName={initialRouteName}>
      <Stack.Screen name="Home" options={commonScreenOptions()} component={HomePage} />
      <Stack.Screen name="CountryDetails" options={commonScreenOptions()} component={DetailsPage} />
    </Stack.Navigator>
  )

  // 1.5.3. END .................................................................................
}

// 1.5. END .......................................................................................

export default Root

// END FILE ####################################################################
